### ISSUE TITLE
Callback function passed as an argument to sendMessage is never triggered.

### ISSUE THREAD

**Issue by mkrishnappa** [WinkMeter/flutter_socket_io#10]
I was able to connect to the socket io server and send data to server using sendMessage function.
However, there is a callback function that is passed as an argument to sendMessage function and it is never triggered even though the server has emited a response.

**Comment by wuilmerj24** [comment]
@mkrishnappa Could you solve?

**Comment by vishwajit76** [comment]
I have the same problem.
