### ISSUE TITLE
Swift based application problem with AppDelegate

### ISSUE THREAD

**Issue by TahaMalas** [WinkMeter/flutter_socket_io#20]
Hey! I'm using Swift as the main language for the iOS application but the problem is in the example you provided you're using Obj-C, can you migrate the AppDelegate at least to Swift

**Comment by harivamshi81189** [comment]
> Hey! I'm using Swift as the main language for the iOS application but the problem is in the example you provided you're using Obj-C, can you migrate the AppDelegate at least to Swift

Hey, can I know about the status of the issue u mentioned...? Is it working now...if yes plz help me how to make this plugin work in IOS?
