### ISSUE TITLE
how do i send header data? 

### ISSUE THREAD

**Issue by rajeshzmoke** [WinkMeter/flutter_socket_io#21]
i need to send header with accesstoken and chatroomid ...but there is no way to do it, data sent in query parameter doesnt show in the server side

**Comment by prakashssp077** [comment]
Have a same dout??

**Comment by mawippel** [comment]
You can use the query parameter, it's a String.
If you're using SocketIO on the Server Side, you can access it in the `socket.request._query` property, which is a map.
 Here's an example of a connection code:
`socketIO = SocketIOManager().createSocketIO(
        'http://localhost:3001',
        '/',
        query: 'jwt=YOUR_JWT_HERE',);`
