### ISSUE TITLE
How to reduce log messages in the console?

### ISSUE THREAD

**Issue by Dannark** [WinkMeter/flutter_socket_io#50]
Hey guys, it is Just something i coud not find on the lib yet.
I'm getting a lot of `CALLLING FUNCTION` or `sendMessage(31106)` logs.

By the way, it is working really well so far. Thanks.

**Comment by Dannark** [comment]
Never mind, I just figured it out. Thanks

**Comment by SupertigerDev** [comment]
how did you do it?

**Comment by Dannark** [comment]
First you need to edit the two .dart files. Search for the `print` lines and comment them:
![print1](https://user-images.githubusercontent.com/7622553/89103545-f389f700-d3e8-11ea-84dd-0ba70fcae68a.png)

Like so:
![print2](https://user-images.githubusercontent.com/7622553/89103574-2fbd5780-d3e9-11ea-9da1-0b5e6c8c2b60.png)

Them you need to comment the prints logs `Utils.log()` from the java class whitch in my case is located in:
 `C:\development\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_socket_io-0.6.0`

Edit the `SocketIO.java` in my case I only commented the lines: 332, 214 but you can comment others logs if you want
Also the `SocketIOManager.java` in the line: 28
And the `FlutterSocketIoPlugin.java` at 39

**Comment by SupertigerDev** [comment]
I changed to another lib as this one keeps crashing but thanks a lot. hopefully this will help others

**Comment by Dannark** [comment]
Yeah i will do the same.
